import type { Metadata } from 'next'
import SessionProvider from '../components/session-provider'
import './globals.css'
import { ReactNode } from 'react'
import { getServerSession } from 'next-auth/next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function asuRootLayout({
                                              children,
                                            }: Readonly<{
  children: ReactNode
}>) {
  const session = await getServerSession()

  return (
    <html lang="en">
    <body>
    <SessionProvider session={session}>{children}</SessionProvider>
    </body>
    </html>
  )
}
